default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: RoboCitizen_Devdb

test:
  <<: *default
  database: RoboCitizen_Testdb

production:
  <<: *default
  database: db/production.sqlite3
