Rails.application.routes.draw do

  get 'home/alabama' => 'home#alabama'
  get 'home/alaska' => 'home#alaska'
  get 'home/arkansas' => 'home#arkansas'
  get 'home/arizona' => 'home#arizona'
  get 'home/california' => 'home#california'
  get 'home/colorado' => 'home#colorado'
  get 'home/connecticut' => 'home#connecticut'
  get 'home/delaware' => 'home#delaware'
  get 'home/florida' => 'home#florida'
  get 'home/georgia' => 'home#georgia'
  get 'home/hawaii' => 'home#hawaii'
  get 'home/indiana' => 'home#indiana'
  get 'home/iowa' => 'home#iowa'
  get 'home/kansas' => 'home#kansas'
  get 'home/kentucky' => 'home#kentucky'
  get 'home/louisiana' => 'home#louisiana'
  get 'home/maine' => 'home#maine'
  get 'home/maryland' => 'home#maryland'
  get 'home/massachusetts' => 'home#massachusetts'
  get 'home/michigan' => 'home#michigan'
  get 'home/minnesota' => 'home#minnesota'
  get 'home/mississippi' => 'home#mississippi'
  get 'home/missouri' => 'home#missouri'
  get 'home/montana' => 'home#montana'
  get 'home/nebraska' => 'home#nebraska'
  get 'home/nevada' => 'home#nevada'
  get 'home/newhampshire' => 'home#newhampshire'
  get 'home/newjersey' => 'home#newjersey'
  get 'home/newmexico' => 'home#newmexico'
  get 'home/newyork' => 'home#newyork'
  get 'home/northcarolina' => 'home#northcarolina'
  get 'home/northdakota' => 'home#northdakota'
  get 'home/ohio' => 'home#ohio'
  get 'home/oklahoma' => 'home#oklahoma'
  get 'home/oregon' => 'home#oregon'
  get 'home/pennsylvania' => 'home#pennsylvania'
  get 'home/rhodeisland' => 'home#rhodeisland'
  get 'home/southcarolina' => 'home#southcarolina'
  get 'home/tennessee' => 'home#tennessee'
  get 'home/texas' => 'home#texas'
  get 'home/utah' => 'home#utah'
  get 'home/vermont' => 'home#vermont'
  get 'home/virginia' => 'home#virginia'
  get 'home/washington' => 'home#washington'
  get 'home/westvirginia' => 'home#westvirginia'
  get 'home/wisconsin' => 'home#wisconsin'
  get 'home/wyoming' => 'home#wyoming'

  root to: redirect('/legislators')
  get '/legislators', to: "home#index"

end
